apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::156655151599:role/bedrock_nodes-eks-node-group-20260209211013616600000001
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
  mapUsers: |
    - userarn: arn:aws:iam::156655151599:user/bedrock-dev-view
      username: bedrock-dev-view
      groups:
        - view-role-group
